name:                simple-lang
version:             0.1.0.0
github:              "rmullin7286/simple-lang"
license:             GPL-3
author:              "Ryan Mullin"
maintainer:          "ryan.mullin12@gmail.com"
copyright:           "2020 Ryan Mullin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-lang#readme>

dependencies:
- base >= 4.9 && < 5
- megaparsec >= 8.0.0
- text >= 1.2.4.0
- containers >= 0.6.2.1
- mtl >= 2.2.2
- text-show >= 3.8.5
- argparser >= 0.3.4
- filepath >= 1.4.2.1
- directory >= 1.3.6.1
- extra >= 1.7.1

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - DerivingVia
  - DeriveGeneric
  - TypeApplications
  - RecordWildCards

executables:
  slc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XOverloadedStrings
    dependencies:
    - simple-lang

tests:
  simple-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - OverloadedStrings
    - DerivingVia
    - DeriveGeneric
    - TypeApplications
    - RecordWildCards
    dependencies:
    - simple-lang
    - hspec
    build-tools:
    - hspec-discover
